### ISSUE TITLE
tainttests/unit_tests.js fails at the Array join test

### ISSUE THREAD

**Issue by dmitris** [wisec/DOMinator#3]
Array map new Array A string AAAAAAAAAAAAAAAAAAAAAA.tainted false
Array map new Array A string abcdefghilmnopqrstuvz.tainted true
Array map new Array A string 1234567890.tainted true
Array join v.tainted
[Ko]

**Comment by wisec** [comment]
Sorry,it's my fault.. it's a lack of verbosity. 
It means that there are no [Ko].
If there is some Ko it shows after the [Ko].
Since there's no Ko then Ko is empty. 
I'll modify it to say everything went ok if Ko is zero length.

Thanks

**Comment by dmitris** [comment]
yes, just figured it out :)

I'd suggest the following change to hide the[Ko] - you can also add an else clause to print "OK all tests"
instead of:
print("[Ko] "+assertsKo.join(" "));

put:
if (assertsKo.length > 0) {  
 print("[Ko] "+assertsKo.join(" "));
}

**Comment by wisec** [comment]
I just commited something like that :)
