### ISSUE TITLE
installation of DOMinator on Mac Lion

### ISSUE THREAD

**Issue by neraliu** [wisec/DOMinator#4]
Hello wisec

i have compiled the DOMinator successfully on the Mac Lion machine recently with some adjustment in this branch
https://github.com/neraliu/DOMinator/tree/maclionbuild

uname -a
Darwin clockenemy-lm 11.4.0 Darwin Kernel Version 11.4.0: Mon Apr  9 19:33:05 PDT 2012; root:xnu-1699.26.8~1/RELEASE_I386 i386 i386

however, when i follow this installation instruction, i found out that the DOMinator Extension is missing in the final build, am i missing something?
http://code.google.com/p/dominator/wiki/InstallationInstructions

**Comment by dmitris** [comment]
Nera - the current DOMinator Firefox extension is not part of the open source project, it is a commercial product that can be licensed from the MindedSecurity - see https://dominator.mindedsecurity.com/.  A 15-day trial version is available.
An older version of the Firefox extension is also available http://code.google.com/p/dominator/downloads/list (but it should be used with the corresponding version of the modified Firefox).

From an offline discussions with Nera - I believe the successful compilation was done on an 32-bit Mac using older Xcode / gcc.  I don't think it would work on a 64-bit Lion with newer Xcode and /Developer removed as recommended by Apple - Nera, please let us know if it is not so (would love to be able to build the current codebase on a modern Mac).

I think the older documentation on code.google.com may be misleading for this project and would suggest to consolidation the currently relevant documentation on the Github while clearly marking the code.google.com documents as outdated / deprecated.

**Comment by wisec** [comment]
Sorry @neraliu  and @dmitris,
I completely missed the issue... 
@neraliu you'll have the binaries in ff-taintOPT/dist/bin/ directory although you'll miss the extension (community version) which will be released by the end of the year. 

On the other side, as Dmitri already said it would be great to have the DOMinator Core compiled for Mac, so,
Let's keep this issue still open to see if we can manage to compile it or another version on Mac.

Finally, @dmitris you're definitely right. I need to rearrange the google repo and doc.

**Comment by wisec** [comment]
Just committed a mozconfig and a jsapi.h mod that allow leopard compilation.

**Comment by dmitris** [comment]
Do you think it would work for Lion - or would we need to take a later version of Firefox as the basis?
