### ISSUE TITLE
upgrade the underlying FF version to ensure WebDriver automation support in the future

### ISSUE THREAD

**Issue by dmitris** [wisec/DOMinator#6]
http://seleniumhq.wordpress.com/2013/01/22/a-plan-to-drop-firefox-3-x-support/

"Once support for Firefox 3.x is removed, the earliest supported Firefox version will be the ESR-1 release (currently Firefox 10)." - I wonder if this would affect the ability to automate DOMinator with WebDriver

**Comment by wisec** [comment]
DOMinator Core based on 3.6 is the old version of this one, and is on google code.
This version is based on firefox 8.0 and according to my internal code selenium with python bindings still work. 
I'll keep you posted 
Thanks

**Comment by dmitris** [comment]
yes, it works with the present WebDriver (selenium) but according to the link above, they want to remove support of FF versions prior to 10 in the shortly upcoming releases.  So people may not be able to automate DOMinator with Selenium that comes out later in the year.

**Comment by dmitris** [comment]
I'm going to close the issue - there are other reasons to update the underlying FF version of DOMinator (for example, to be able to compile it with the current Mac toolchain), and it's a big project.
