### ISSUE TITLE
make the DOMinator code compile on 64-bit Linux and newer compiler chain

### ISSUE THREAD

**Issue by dmitris** [wisec/DOMinator#7]
Fedora 17 is 64-bit Linux, would be great to be able to compile DOMinator on it with a newer compiler toolchain (such as gcc-4.7).  Some code changes (in the stock FF code, unrelated to the tainted part) would be needed.

**Comment by wisec** [comment]
Thanks,
let me find the changes and I'll commit them asap.

**Comment by dmitris** [comment]
closing due to age
