### ISSUE TITLE
duplicate tests in taint test/unit_tests.js (Object keys)

### ISSUE THREAD

**Issue by dmitris** [wisec/DOMinator#9]
It seems to me that the tests on 
https://github.com/wisec/DOMinator/blob/master/tainttests/unit_tests.js#L27
and 
https://github.com/wisec/DOMinator/blob/master/tainttests/unit_tests.js#L42
are identical - is it so?  

The comment for the second one says "Yet to implement" but I believe it is implemented and works now...

Unless I'm missing some details, I suggest to remove the second test (and add missing semicolons :)  ).

**Comment by wisec** [comment]
It seems so,  
thanks !  I'll remove it.
